# Generated by Django 5.2.7 on 2025-10-22 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ikona')),
            ],
            options={
                'verbose_name': 'Material kategoriyasi',
                'verbose_name_plural': 'Material kategoriyalari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('material_type', models.CharField(choices=[('presentation', 'PPT taqdimot'), ('document', 'Word hujjat'), ('handout', 'Tarqatma material'), ('worksheet', 'Ish varaqasi'), ('test', 'Test'), ('methodology', 'Metodika'), ('fact', 'Qiziqarli fakt'), ('other', 'Boshqa')], max_length=20, verbose_name='Material turi')),
                ('file', models.FileField(upload_to='materials/', verbose_name='Fayl')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='material_thumbnails/', verbose_name='Kichik rasm')),
                ('tags', models.CharField(blank=True, max_length=500, null=True, verbose_name='Teglar (vergul bilan ajrating)')),
                ('grade_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sinf darajasi')),
                ('is_public', models.BooleanField(default=True, verbose_name='Umumiy foydalanish')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Yuklab olishlar soni')),
                ('rating', models.FloatField(default=0.0, verbose_name='Reyting')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='materials.materialcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiallar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklab olingan vaqt')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='materials.material', verbose_name='Material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_downloads', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Material yuklab olish',
                'verbose_name_plural': 'Material yuklab olishlar',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Reyting')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='materials.material', verbose_name='Material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Material reytingi',
                'verbose_name_plural': 'Material reytinglari',
                'unique_together': {('material', 'user')},
            },
        ),
    ]
