# Generated by Django 4.2.7 on 2025-10-23 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('presentation', 'PPT taqdimot'), ('document', 'Word hujjat'), ('handout', 'Tarqatma material'), ('worksheet', 'Ish varaqasi'), ('test', 'Test'), ('methodology', 'Metodika'), ('fact', 'Qiziqarli fakt'), ('video', 'Video darslik'), ('audio', 'Audio material'), ('image', 'Rasm galereyasi'), ('3d_model', '3D model'), ('interactive', 'Interaktiv material'), ('simulation', 'Simulyatsiya'), ('animation', 'Animatsiya'), ('other', 'Boshqa')], max_length=20, verbose_name='Material turi'),
        ),
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Darslik sarlavhasi')),
                ('description', models.TextField(verbose_name='Darslik tavsifi')),
                ('video_file', models.FileField(upload_to='video_lessons/', verbose_name='Video fayl')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/', verbose_name='Video rasmi')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Davomiyligi (soniya)')),
                ('grade_level', models.CharField(max_length=50, verbose_name='Sinf darajasi')),
                ('subject', models.CharField(max_length=50, verbose_name='Fan')),
                ('tags', models.CharField(blank=True, max_length=500, null=True, verbose_name='Teglar')),
                ('is_public', models.BooleanField(default=True, verbose_name='Umumiy foydalanish')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rilganlar soni")),
                ('rating', models.FloatField(default=0.0, verbose_name='Reyting')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_lessons', to='materials.materialcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Video darslik',
                'verbose_name_plural': 'Video darsliklar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Model sarlavhasi')),
                ('description', models.TextField(verbose_name='Model tavsifi')),
                ('model_file', models.FileField(upload_to='3d_models/', verbose_name='3D model fayli')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='3d_thumbnails/', verbose_name='Model rasmi')),
                ('model_type', models.CharField(choices=[('educational', "Ta'limiy"), ('scientific', 'Ilmiy'), ('historical', 'Tarixiy'), ('biological', 'Biologik'), ('geological', 'Geologik'), ('architectural', 'Arxitektura'), ('artistic', 'Badiiy'), ('technical', 'Texnik')], max_length=20, verbose_name='Model turi')),
                ('grade_level', models.CharField(max_length=50, verbose_name='Sinf darajasi')),
                ('subject', models.CharField(max_length=50, verbose_name='Fan')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Fayl hajmi (bayt)')),
                ('is_interactive', models.BooleanField(default=False, verbose_name='Interaktiv')),
                ('is_public', models.BooleanField(default=True, verbose_name='Umumiy foydalanish')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Yuklab olishlar soni')),
                ('rating', models.FloatField(default=0.0, verbose_name='Reyting')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models_3d', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models_3d', to='materials.materialcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': '3D model',
                'verbose_name_plural': '3D modellar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Topshiriq sarlavhasi')),
                ('description', models.TextField(verbose_name='Topshiriq tavsifi')),
                ('assignment_type', models.CharField(choices=[('homework', 'Uy vazifasi'), ('classwork', 'Dars ishi'), ('project', 'Loyiha'), ('research', 'Tadqiqot'), ('presentation', 'Taqdimot'), ('test_assignment', 'Test topshirish'), ('creative', 'Ijodiy ish'), ('practical', 'Amaliy ish')], max_length=20, verbose_name='Topshiriq turi')),
                ('grade_level', models.CharField(max_length=50, verbose_name='Sinf darajasi')),
                ('subject', models.CharField(max_length=50, verbose_name='Fan')),
                ('due_date', models.DateTimeField(verbose_name='Topshiriq muddati')),
                ('max_points', models.PositiveIntegerField(default=100, verbose_name='Maksimal ball')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ko'rsatmalar")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='materials.materialcategory', verbose_name='Kategoriya')),
                ('materials', models.ManyToManyField(blank=True, related_name='assignments', to='materials.material', verbose_name='Kerakli materiallar')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Topshiriq',
                'verbose_name_plural': 'Topshiriqlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name="O'quvchi ismi")),
                ('student_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sinf')),
                ('student_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name="O'quvchi email")),
                ('submission_text', models.TextField(blank=True, null=True, verbose_name='Matnli javob')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('submitted', 'Topshirilgan'), ('graded', 'Baholangan'), ('returned', 'Qaytarilgan')], default='draft', max_length=20, verbose_name='Holat')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Topshirilgan vaqt')),
                ('grade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Olingan ball')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name="O'qituvchi izohi")),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Baholangan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='materials.assignment', verbose_name='Topshiriq')),
                ('attached_files', models.ManyToManyField(blank=True, related_name='submission_attachments', to='materials.material', verbose_name='Ilova fayllar')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL, verbose_name="Baholagan o'qituvchi")),
            ],
            options={
                'verbose_name': "O'quvchi topshirig'i",
                'verbose_name_plural': "O'quvchi topshirig'lari",
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student_email')},
            },
        ),
    ]
