# Generated by Django 5.2.7 on 2025-10-22 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel_exports/', verbose_name='Excel fayl')),
                ('total_students', models.PositiveIntegerField(default=0, verbose_name="Jami o'quvchilar soni")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_exports', to='tests.test', verbose_name='Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_exports', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Excel eksport',
                'verbose_name_plural': 'Excel eksportlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OCRProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ocr_images/', verbose_name='Rasm')),
                ('processed_text', models.TextField(blank=True, null=True, verbose_name='Qayta ishlangan matn')),
                ('confidence_score', models.FloatField(default=0.0, verbose_name='Ishonch darajasi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Qayta ishlanmoqda'), ('completed', 'Tugatilgan'), ('failed', 'Xatolik')], default='pending', max_length=20, verbose_name='Holat')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Xatolik xabari')),
                ('processing_time', models.FloatField(default=0.0, verbose_name='Qayta ishlash vaqti (soniya)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugatilgan vaqt')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocr_processings', to='tests.test', verbose_name='Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_processings', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'OCR qayta ishlash',
                'verbose_name_plural': 'OCR qayta ishlashlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name="O'quvchi ismi")),
                ('student_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sinf')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Jami savollar')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar")),
                ('wrong_answers', models.PositiveIntegerField(default=0, verbose_name="Noto'g'ri javoblar")),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Ball')),
                ('percentage', models.FloatField(default=0.0, verbose_name='Foiz')),
                ('grade', models.CharField(blank=True, max_length=10, null=True, verbose_name='Baholash')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='Qayta ishlangan vaqt')),
                ('ocr_processing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_result', to='ocr_processing.ocrprocessing', verbose_name='OCR qayta ishlash')),
            ],
            options={
                'verbose_name': 'Test natijasi',
                'verbose_name_plural': 'Test natijalari',
                'ordering': ['-processed_at'],
            },
        ),
    ]
