# Generated by Django 5.2.7 on 2025-10-22 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Savol matni')),
                ('question_type', models.CharField(choices=[('single_choice', 'Bitta javob tanlash'), ('multiple_choice', 'Bir nechta javob tanlash'), ('true_false', "To'g'ri/Noto'g'ri"), ('fill_blank', "Bo'sh joyni to'ldirish"), ('essay', 'Erkin javob')], default='single_choice', max_length=20, verbose_name='Savol turi')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Ball')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartib raqami')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Tushuntirish')),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Savol rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Test kategoriyasi',
                'verbose_name_plural': 'Test kategoriyalari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Javob matni')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartib raqami')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': 'Javoblar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Test sarlavhasi')),
                ('description', models.TextField(verbose_name='Test tavsifi')),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rta"), ('hard', 'Qiyin')], default='medium', max_length=10, verbose_name='Qiyinlik darajasi')),
                ('grade_level', models.CharField(max_length=50, verbose_name='Sinf darajasi')),
                ('subject', models.CharField(max_length=50, verbose_name='Fan')),
                ('time_limit', models.PositiveIntegerField(default=60, verbose_name='Vaqt chegarasi (daqiqa)')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Jami savollar soni')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='Jami ball')),
                ('is_public', models.BooleanField(default=True, verbose_name='Umumiy foydalanish')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='tests.testcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.test', verbose_name='Test'),
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name="O'quvchi ismi")),
                ('student_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sinf')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugatilgan vaqt')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Olingan ball')),
                ('percentage', models.FloatField(default=0.0, verbose_name='Foiz')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tugatilgan')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tests.test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Test topshirish',
                'verbose_name_plural': 'Test topshirishlar',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True, verbose_name='Matnli javob')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri")),
                ('points_earned', models.PositiveIntegerField(default=0, verbose_name='Olingan ball')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Javob berilgan vaqt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='tests.question', verbose_name='Savol')),
                ('selected_answers', models.ManyToManyField(related_name='student_selections', to='tests.answer', verbose_name='Tanlangan javoblar')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='tests.testattempt', verbose_name='Test topshirish')),
            ],
            options={
                'verbose_name': "O'quvchi javobi",
                'verbose_name_plural': "O'quvchi javoblari",
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
